### ISSUE TITLE
make this a pull req

### ISSUE THREAD

**Issue by darkstarre** [CodePlatoon/daily#3]
- [ ] do rails overview in the morning Monday
   -workflow/integrating notes app
- [ ] do .JS lecture on Tuesday morning
   - D3
- [ ] SQLite, Git, erb, capybara, testing mini classes, moar databasesesesesesesesesese
- [ ] analysis of project making i.e approaches.
- [ ]  expand on this list whomever does it.

**Comment by darkstarre** [comment]
@JoshCheek @javi-rev @101glover @jamesmarkwilton @matthewswan @seangallen

**Comment by JoshCheek** [comment]
@101glover made it a [PR](https://github.com/CodePlatoon/daily/pull/4) :) it hits most of these.

I'll give anyone direct commit access, after they've had 4 pull requests get merged!

**Comment by JoshCheek** [comment]
If you're wanting me to do something for "Rails lecture and conversation" (ie lecture on what?) then update it with info about what you'd like me to focus on.
